// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaELearning.Data;

#nullable disable

namespace PlataformaELearning.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260318020216_AddApartadosTareasYEntregas")]
    partial class AddApartadosTareasYEntregas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlataformaELearning.Models.ApartadoCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("IX_Apartado_CursoId");

                    b.ToTable("ApartadosCursos");
                });

            modelBuilder.Entity("PlataformaELearning.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int?>("EntregaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCalificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Puntuacion")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int?>("TareaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("TareaId");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("PlataformaELearning.Models.ContenidoCurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ArchivoFisico")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContenidoTexto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlVideo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("IX_ContenidoCurso_CursoId");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IX_ContenidoCurso_Tipo");

                    b.ToTable("ContenidosCursos");
                });

            modelBuilder.Entity("PlataformaELearning.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaestroId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaestroId")
                        .HasDatabaseName("IX_Curso_MaestroId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("PlataformaELearning.Models.EntregaTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ArchivoEntregado")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("CalificacionId")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioAlumno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TareaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId")
                        .HasDatabaseName("IX_Entrega_AlumnoId");

                    b.HasIndex("CalificacionId")
                        .IsUnique()
                        .HasFilter("[CalificacionId] IS NOT NULL");

                    b.HasIndex("TareaId")
                        .HasDatabaseName("IX_Entrega_TareaId");

                    b.ToTable("EntregasTareas");
                });

            modelBuilder.Entity("PlataformaELearning.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CursoId");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("PlataformaELearning.Models.MaterialTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ArchivoFisico")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContenidoTexto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TareaId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlVideo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.ToTable("MaterialesTarea");
                });

            modelBuilder.Entity("PlataformaELearning.Models.TareaApartado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartadoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<int>("PuntosTotales")
                        .HasColumnType("int");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApartadoId")
                        .HasDatabaseName("IX_Tarea_ApartadoId");

                    b.HasIndex("FechaLimite")
                        .HasDatabaseName("IX_Tarea_FechaLimite");

                    b.ToTable("TareasApartados");
                });

            modelBuilder.Entity("PlataformaELearning.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlataformaELearning.Models.ApartadoCurso", b =>
                {
                    b.HasOne("PlataformaELearning.Models.Curso", "Curso")
                        .WithMany("Apartados")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("PlataformaELearning.Models.Calificacion", b =>
                {
                    b.HasOne("PlataformaELearning.Models.User", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaELearning.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaELearning.Models.TareaApartado", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId");

                    b.Navigation("Alumno");

                    b.Navigation("Curso");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("PlataformaELearning.Models.ContenidoCurso", b =>
                {
                    b.HasOne("PlataformaELearning.Models.Curso", "Curso")
                        .WithMany("Contenidos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("PlataformaELearning.Models.Curso", b =>
                {
                    b.HasOne("PlataformaELearning.Models.User", "Maestro")
                        .WithMany()
                        .HasForeignKey("MaestroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maestro");
                });

            modelBuilder.Entity("PlataformaELearning.Models.EntregaTarea", b =>
                {
                    b.HasOne("PlataformaELearning.Models.User", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlataformaELearning.Models.Calificacion", "Calificacion")
                        .WithOne("Entrega")
                        .HasForeignKey("PlataformaELearning.Models.EntregaTarea", "CalificacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlataformaELearning.Models.TareaApartado", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Calificacion");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("PlataformaELearning.Models.Inscripcion", b =>
                {
                    b.HasOne("PlataformaELearning.Models.User", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaELearning.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("PlataformaELearning.Models.MaterialTarea", b =>
                {
                    b.HasOne("PlataformaELearning.Models.TareaApartado", "Tarea")
                        .WithMany("Materiales")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("PlataformaELearning.Models.TareaApartado", b =>
                {
                    b.HasOne("PlataformaELearning.Models.ApartadoCurso", "Apartado")
                        .WithMany("Tareas")
                        .HasForeignKey("ApartadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartado");
                });

            modelBuilder.Entity("PlataformaELearning.Models.ApartadoCurso", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("PlataformaELearning.Models.Calificacion", b =>
                {
                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("PlataformaELearning.Models.Curso", b =>
                {
                    b.Navigation("Apartados");

                    b.Navigation("Contenidos");
                });

            modelBuilder.Entity("PlataformaELearning.Models.TareaApartado", b =>
                {
                    b.Navigation("Materiales");
                });
#pragma warning restore 612, 618
        }
    }
}
